/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowBienvenueclient;
  GtkWidget *affich_res_h;
  GtkWidget *affich_v;
  GtkWidget *affich_res_voi;
  GtkWidget *modif_res_h;
  GtkWidget *modif_res_v;
  GtkWidget *modifier_res_vo;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowBienvenueclient = create_windowBienvenueclient ();
  gtk_widget_show (windowBienvenueclient);
  /*affich_res_h = create_affich_res_h ();
  gtk_widget_show (affich_res_h);
  affich_v = create_affich_v ();
  gtk_widget_show (affich_v);
  affich_res_voi = create_affich_res_voi ();
  gtk_widget_show (affich_res_voi);
  modif_res_h = create_modif_res_h ();
  gtk_widget_show (modif_res_h);
  modif_res_v = create_modif_res_v ();
  gtk_widget_show (modif_res_v);
  modifier_res_vo = create_modifier_res_vo ();
  gtk_widget_show (modifier_res_vo);*/

  gtk_main ();
  return 0;
}

